env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  jQuery: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
